export const sampleSelectStock = {
  request: {
    'ckid': '',
    'inp': [
      {
        'ckcw': '',
        'days': '',
        'itbz': '',
        'spbh': '',
        'spbhid': '',
        'spcd': '',
        'spckid': '',
        'spckmc': '',
        'spcwid': '',
        'spcwid2': '',
        'spgh': '',
        'spjs': '',
        'spjs2': '',
        'spjsl': '',
        'spkhmc': '',
        'spkhmcid': '',
        'spsl': '',
        'sptm': '',
        'sptmc': '',
        'spzs': '',
        'ssrqid': '',
        'ssrqidn': ''
      }
    ],
    'isBa': '',
    'khlx': '',
    'khmc': '',
    'khmcid': '',
    'khpb': 0,
    'liid_1': '',
    'shopId': 0,
    'spbh': '',
    'spcd': '',
    // 'spckid': '',
    'spckidis': [],
    'spcwid2': '',
    'spgh': '',
    'spmc': '',
    'sptm': '',
    'spzs': ''
  },
  response: {
    'total': 0,
    'rows': [
      {
        'spbhid': '',
        'sptmc': '',
        'sptm': '',
        'spzs': '',
        'spmc': '',
        'spcd': '',
        'spgh': '',
        'spbh': '',
        'spkhmc': '',
        'change': '',
        'spkhmcid': '',
        'spckmc': '',
        'spckid': '',
        'spcwid': '',
        'ckcw': '',
        'spdm': '',
        'liidn': '',
        'ssrqid': '',
        'ssrqidn': '',
        'days': '',
        'wpggA': '',
        'wpggB': '',
        'wpggC': '',
        'wpggD': '',
        'wpggE': '',
        'wpggF': '',
        'wpggG': '',
        'wpggH': '',
        'spjs2': '',
        'spjsl': '',
        'spsl2': '',
        'spjsz': '',
        'spslz': ''
      }
    ],
    'code': 0,
    'msg': ''
  }
}
